#!/usr/bin/env python3
"""
Test script for Regulatory Compliance Framework Integration
Phase 4.1.3.1: Testing regulatory compliance integration with quality assurance
"""

import os
import sys
from pathlib import Path

# Add automation directory to path
sys.path.append(str(Path(__file__).parent))

from quality_assurance_framework import QualityAssuranceFramework

def test_regulatory_compliance_integration():
    """Test the regulatory compliance framework integration"""

    print("🧪 Testing Regulatory Compliance Framework Integration")
    print("=" * 60)

    # Initialize the quality assurance framework
    qa_framework = QualityAssuranceFramework()

    # Test documents to assess
    test_docs = [
        "../README.md",
        "docs/README.md",
        "docs/TERMINAL_GROUNDS_MASTER_ROADMAP_2025.md",
        "docs/PHASE_4_1_CONTENT_GOVERNANCE_ROADMAP.md"
    ]

    successful_assessments = 0
    total_assessments = len(test_docs)

    for doc_path in test_docs:
        if not os.path.exists(doc_path):
            print(f"⚠️  Skipping {doc_path} - file not found")
            continue

        print(f"\n📄 Assessing: {doc_path}")
        print("-" * 40)

        try:
            # Perform complete quality assessment (including compliance)
            report = qa_framework.perform_complete_quality_assessment(doc_path)

            # Display compliance results
            compliance = report.compliance_results
            print("✅ Compliance Assessment:")
            print(f"   Score: {compliance.get('compliance_score', 0):.1f}%")
            print(f"   Status: {compliance.get('overall_status', 'unknown').title()}")
            print(f"   Violations: {compliance.get('violations_count', 0)}")

            if compliance.get('violations'):
                print("   Issues Found:")
                for violation in compliance['violations'][:3]:  # Show first 3
                    print(f"     - {violation['description']} ({violation['severity']})")
                if len(compliance['violations']) > 3:
                    print(f"     ... and {len(compliance['violations']) - 3} more")

            if compliance.get('recommendations'):
                print("   Recommendations:")
                for rec in compliance['recommendations'][:2]:  # Show first 2
                    print(f"     • {rec}")

            successful_assessments += 1

        except Exception as e:
            print(f"❌ Error assessing {doc_path}: {e}")

    print(f"\n{'='*60}")
    print("📊 Integration Test Results:")
    print(f"   Successful Assessments: {successful_assessments}/{total_assessments}")
    print(f"   Success Rate: {(successful_assessments/total_assessments)*100:.1f}%")
    # Generate compliance report
    print("📋 Generating Compliance Report...")
    compliance_report = qa_framework.compliance_framework.generate_compliance_report()
    print("Compliance report generated successfully!")

    # Save detailed report
    report_path = "compliance_test_report.md"
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(compliance_report)
    print(f"📄 Detailed report saved to: {report_path}")

    return successful_assessments == total_assessments

if __name__ == "__main__":
    success = test_regulatory_compliance_integration()
    if success:
        print("\n🎉 Regulatory Compliance Framework Integration Test PASSED!")
        sys.exit(0)
    else:
        print("\n❌ Regulatory Compliance Framework Integration Test FAILED!")
        sys.exit(1)

# Pseudocode generated by codewrx.ai
