name: Build Linux Server
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
jobs:
  docs-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docs gate
        run: |
          python3 -m pip install --upgrade pip
          python3 - <<'PY'
          import sys, subprocess
          from pathlib import Path
          p = Path('Tools/docs_gate.py')
          if not p.exists():
              print('Docs gate script missing at Tools/docs_gate.py')
              sys.exit(1)
          subprocess.check_call([sys.executable, str(p)])
          PY
  build:
    runs-on: [self-hosted, ue5]
    needs: [docs-gate]
    steps:
      - uses: actions/checkout@v4
      - name: Generate Project Files
        shell: bash
        run: |
          ./Engine/Build/BatchFiles/RunUAT.sh BuildGraph -target=MakeProjectFiles -script=Engine/Build/InstalledEngineBuild.xml
      - name: Build Client and Server
        shell: bash
        run: |
          # Cook and build LinuxServer
          ./Engine/Build/BatchFiles/RunUAT.sh BuildCookRun \
            -project=$(pwd)/TerminalGrounds.uproject \
            -noP4 -server -serverplatform=Linux \
            -cook -allmaps -stage -pak -archive \
            -archivedirectory=$(pwd)/Artifacts/LinuxServer
          # Cook and build Client
          ./Engine/Build/BatchFiles/RunUAT.sh BuildCookRun \
            -project=$(pwd)/TerminalGrounds.uproject \
            -noP4 -client -clientplatform=Linux \
            -cook -allmaps -stage -pak -archive \
            -archivedirectory=$(pwd)/Artifacts/LinuxClient
      - name: Run Gauntlet Smoke Tests
        shell: bash
        run: |
          # Placeholder for Gauntlet tests
          echo "Gauntlet smoke tests: join/fire/hitreg/extract/vehicle/mission"
      - name: Collect Performance Metrics
        shell: bash
        run: |
          # Placeholder for performance metrics collection
          echo "Collecting frame ms, draw calls, Niagara counts"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TerminalGrounds-Linux-Builds
          path: |
            Artifacts/LinuxServer/**
            Artifacts/LinuxClient/**
