name: Build Linux Server
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: [ self-hosted, ue5 ]
    steps:
      - uses: actions/checkout@v4
      - name: Generate Project Files
        run: |
          ./Engine/Build/BatchFiles/RunUAT.sh BuildGraph -target=MakeProjectFiles -script=Engine/Build/InstalledEngineBuild.xml
      - name: Build Server
        run: |
          ./Engine/Build/BatchFiles/RunUAT.sh BuildCookRun \
            -project=$(pwd)/TerminalGrounds.uproject \
            -noP4 -server -serverplatform=Linux \
            -cook -allmaps -stage -pak -archive \
            -archivedirectory=$(pwd)/Artifacts/LinuxServer
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LinuxServer
          path: Artifacts/LinuxServer/**
