name: Docs and Assets Gate

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-assets:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow PyYAML requests
    
    - name: Run placeholder validation
      run: python Tools/Validation/validate_placeholders.py --check-manifest
      
    - name: Upload placeholder report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: placeholder-report
        path: Docs/.placeholder_report.json
    
    - name: Check manifest integrity
      run: |
        python -c "
        import json
        from pathlib import Path
        manifest = Path('Docs/Concepts/ASSET_MANIFEST.json')
        if manifest.exists():
            with open(manifest) as f:
                data = json.load(f)
                print(f'Manifest contains {len(data)} assets')
        else:
            print('WARNING: No manifest found')
        "
    
    - name: Validate documentation
      run: |
        $requiredDocs = @(
          'README.md',
          'Docs/Art/ART_BIBLE.md',
          'Docs/VFX/VFX_BIBLE.md',
          'Docs/Art/UI_STYLE_GUIDE.md',
          'Docs/Phase4_Implementation_Log.md'
        )
        
        foreach ($doc in $requiredDocs) {
          if (Test-Path $doc) {
            Write-Host "✓ Found: $doc"
          } else {
            Write-Host "✗ Missing: $doc"
            exit 1
          }
        }
